BN:
  WEIGHT_DECAY: 0.0
PRETRAIN:
  DATASET: ACAV
  BATCH_SIZE: 64
  SAVE_PERIOD: 500
  SAVE_EVERY_EPOCH: 100
  PREEMPTIBLE: True
CONTRAST:
  PROJECTION_SIZE: 128
  TEMPERATURE: 0.1
  USE_GLOBAL_BATCH: True
VIS:
  ARCH: resnet
  MODEL_NAME: ResNet
RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  SPATIAL_STRIDES: [[1], [2], [2], [2]]
  SPATIAL_DILATIONS: [[1], [1], [1], [1]]
AUD:
  ARCH: resnet
  MODEL_NAME: AudioResNet
AUDIO_RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 32
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  STRIDES: [2, 2, 2, 2]
  DILATIONS: [1, 1, 1, 1]
MODEL:
  TASK: Contrast
  FC_INIT_STD: 0.01
  ZERO_INIT_FINAL_BN: True
  EPSILON: 1e-5
  MOMENTUM: 0.1
DATA:
  CROP_SIZE: 224
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TARGET_FPS: 30
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  PRETRAIN_CROP_SIZE: 224
  PRETRAIN_JITTER_SCALES: [256, 320]
  TARGET_AUDIO_RATE: 44100
  AUDIO_FREQUENCY: 80
  AUDIO_TIME: 128
  FREQUENCY_MASK_RATE: 0.05
  TIME_MASK_RATE: 0.05
  TRANSFORMATIONS: ["resize_crop", "flip", "color_normalize"]
SOLVER:
  BASE_LR: 1e-3
  LR_POLICY: linear
  MAX_EPOCH: 50
  WEIGHT_DECAY: 1e-5
  WARMUP_START_LR: 0.0
  WARMUP_STEPS: 2000
  OPTIMIZING_METHOD: adamw
  USE_AMSGRAD: True
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
LOG_PERIOD: 50
