BN:
  WEIGHT_DECAY: 0.0
TRAIN:
  ENABLE: True
  DATASET: UCF101
  DATASET_SPLIT: 1
  NUM_SAMPLES: 10
  BATCH_SIZE: 64
  SAVE_EVERY_EPOCH: 20
  TEST_PERIOD: 1
  PREEMPTIBLE: False
VAL:
  ENABLE: False
  DATASET: UCF101
  DATASET_SPLIT: 1
TEST:
  ENABLE: False
  DATASET: UCF101
  DATASET_SPLIT: 1
  NUM_SAMPLES: 30
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
  BATCH_SIZE: 64
VIS:
  ARCH: resnet
  MODEL_NAME: ResNet
RESNET:
  TRANS_FUNC: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  INPLACE_RELU: True
  STRIDE_1X1: False
  DEPTH: 50
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
  SPATIAL_STRIDES: [[1], [2], [2], [2]]
  SPATIAL_DILATIONS: [[1], [1], [1], [1]]
MODEL:
  TASK: VisualClassify
  FC_INIT_STD: 0.01
  ZERO_INIT_FINAL_BN: True
  EPSILON: 1e-5
  MOMENTUM: 0.1
  NUM_CLASSES: 101
  DROPOUT_RATE: 0.5
DATA:
  CROP_SIZE: 224
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TARGET_FPS: 30
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  TRAIN_CROP_SIZE: 224
  TRAIN_JITTER_SCALES: [256, 320]
  TEST_CROP_SIZE: 256
  TRANSFORMATIONS: ["resize_crop", "flip", "color_normalize"]
SOLVER:
  BASE_LR: 1e-2
  LR_POLICY: linear
  MAX_EPOCH: 10
  WEIGHT_DECAY: 5e-6
  WARMUP_START_LR: 0.0
  WARMUP_EPOCHS: 0
  OPTIMIZING_METHOD: adam
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
LOG_PERIOD: 50
